# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac9d439cbf766f2184d496d21eb3a6fe5db05f692cef7b31fea749a4ac007c90f99680a8f00e7e736e53444f65f4432ba18f2ac8b5ee2074de060410b6edfdeb

test:
  secret_key_base: 0b730df711f6bace15351b339bc22259f8939e3f395336263ef330b0375184f24192e816fa834d73303cf7a4b05d982268ace74b8ac68fc6fbdd6c6f3941a4f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
